services:
  postgres:
    image: {{ .Vars.images.postgres.name }}:{{ .Vars.images.postgres.version }}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: '--encoding UTF8 --auth-local=trust --auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      LANG: C
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: {{ .Vars.images.redis.name }}:{{ .Vars.images.redis.version }}
    entrypoint: ['redis-server']
    command: ['--requirepass', "${REDIS_PASSWORD}"]
    restart: unless-stopped

  minio:
    image: {{ .Vars.images.minio.name }}:{{ .Vars.images.minio.version }}
    entrypoint: ['minio']
    command: ['server', '/var/lib/minio/data']
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: "${MINIO_SECRET}"
    volumes:
      - miniodata:/var/lib/minio
    restart: unless-stopped

  nats:
    image: {{ .Vars.images.nats.name }}:{{ .Vars.images.nats.version }}
    entrypoint: ['nats-server']
    command: ['-c', '/etc/nats/server.conf']
    environment:
      NATS_TOKEN: "${NATS_TOKEN}"
    volumes:
      - natsdata:/var/lib/nats
      - ./natsetc:/etc/nats:ro
    restart: unless-stopped

  govlab:
    image: {{ .Vars.images.govlab.name }}:{{ .Vars.images.govlab.version }}
    volumes:
      - ./govconfig:/home/governor/config:ro
      - ../../dc.run/govetc:/etc/governor:ro
      - ./templates:/home/governor/templates:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_web'
      - 'traefik.http.services.govlab.loadbalancer.server.port=8080'
      - 'traefik.http.routers.govlab.entrypoints=web'
      - 'traefik.http.routers.govlab.rule=Host(`{{ .Vars.service.govlab.host }}`) && PathPrefix(`/api`, `/.well-known`)'
      - 'traefik.http.routers.govlab.service=govlab@docker'
    networks:
      - default
      - traefik_web
    depends_on:
      - postgres
      - redis
      - minio
      - nats
    restart: unless-stopped

  govstatic:
    image: {{ .Vars.images.fsserve.name }}:{{ .Vars.images.govlab.version }}
    volumes:
      - ./fsserveconfig:/home/fsserve/config
      - ../../dc.run/static:/home/fsserve/base
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_web'
      - 'traefik.http.services.govstatic.loadbalancer.server.port=8080'
      - 'traefik.http.routers.govstatic.entrypoints=web'
      - 'traefik.http.routers.govstatic.rule=Host(`{{ .Vars.service.govlab.host }}`)'
      - 'traefik.http.routers.govstatic.service=govstatic@docker'
    networks:
      - default
      - traefik_web
    restart: unless-stopped

  mailhog:
    image: {{ .Vars.images.mailhog.name }}:{{ .Vars.images.mailhog.version }}
    restart: unless-stopped

volumes:
  pgdata: {}
  miniodata: {}
  natsdata: {}

networks:
  traefik_web:
    external: true
