services:
  postgres:
    image: {{ .Vars.images.postgres.name }}:{{ .Vars.images.postgres.version }}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: '--encoding UTF8 --auth-local=trust --auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      LANG: C
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  headscale:
    image: {{ .Vars.images.headscale.name }}:{{ .Vars.images.headscale.version }}
    entrypoint: ['headscale']
    command: ['serve']
    environment:
      HEADSCALE_DB_PASS: "${POSTGRES_PASSWORD}"
      HEADSCALE_OIDC_CLIENT_ID: "${OIDC_CLIENT_ID}"
      HEADSCALE_OIDC_CLIENT_SECRET: "${OIDC_CLIENT_SECRET}"
    ports:
      - 8082:8080
    extra_hosts:
      - "governor.dev.localhost:host-gateway"
    volumes:
      - ./headscaleconfig:/etc/headscale:ro
      - ../../dc.run/headscale:/var/run
    depends_on:
      - postgres
      - derper
  derper:
    image: {{ .Vars.images.derper.name }}:{{ .Vars.images.derper.version }}
    ports:
      - 8084:8080
      - 3478:3478/udp
    volumes:
      - ../../dc.run/derper:/var/lib/derper

volumes:
  pgdata: {}
