env_file:
  - ./labpgpass.env
  - ./laboidcclient.env

services:
  postgres:
    image: {{ .Vars.images.postgres.name }}:{{ .Vars.images.postgres.version }}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: '--encoding UTF8 --auth-local=trust --auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      LANG: C
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  headscale:
    image: {{ .Vars.images.headscale.name }}:{{ .Vars.images.headscale.version }}
    entrypoint: headscale
    environment:
      DB_PASS: "${POSTGRES_PASSWORD}"
      OIDC_CLIENT_ID: "${OIDC_CLIENT_ID}"
      OIDC_CLIENT_SECRET: "${OIDC_CLIENT_SECRET}"
    ports:
      - 8082:8080
    volumes:
      - ./headscaleconfig:/etc/headscale:ro
      - ./headscalerun:/var/run

volumes:
  pgdata: {}
