services:
  whoami:
    image: {{ .Vars.images.whoami.name }}:{{ .Vars.images.whoami.version }}
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_web'
      - 'traefik.http.services.whoami.loadbalancer.server.port=8080'
      - 'traefik.http.routers.whoami.entrypoints=web'
      - 'traefik.http.routers.whoami.rule=Host(`{{ .Vars.service.whoami.host }}`)'
      - 'traefik.http.routers.whoami.service=whoami@docker'
    networks:
      - default
      - traefik_web

networks:
  traefik_web:
    external: true
