version: xorkevin.dev/anvil/v1alpha1

vars:
  outputdir: traefik
  images:
    traefik:
      name: traefik
      version: '2.5'
  service:
    traefik:
      port: '80'
      tlsport: '443'
      certresolver:
        caserver: https://acme-v02.api.letsencrypt.org/directory
        email: kevin@xorkevin.com
      dash:
        enabled: false
        host: traefik.lab.xorkevin.com
        tls: true

configtpl: componenttpl.yaml
